/* This file was generated by SableCC (http://www.sablecc.org/). */

package group1.lexer;

import java.io.*;
import java.util.*;
import group1.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(String text, int line, int pos) { return new TComment1(text, line, pos); }
    Token new1(String text, int line, int pos) { return new TComment2(text, line, pos); }
    Token new2(String text, int line, int pos) { return new TSpace(text, line, pos); }
    Token new3(int line, int pos) { return new TClas(line, pos); }
    Token new4(int line, int pos) { return new TPublic(line, pos); }
    Token new5(int line, int pos) { return new TStatic(line, pos); }
    Token new6(int line, int pos) { return new TVoid(line, pos); }
    Token new7(int line, int pos) { return new TMain(line, pos); }
    Token new8(int line, int pos) { return new TString(line, pos); }
    Token new9(int line, int pos) { return new TInt(line, pos); }
    Token new10(int line, int pos) { return new TFloat(line, pos); }
    Token new11(int line, int pos) { return new TFor(line, pos); }
    Token new12(int line, int pos) { return new TWhile(line, pos); }
    Token new13(int line, int pos) { return new TIf(line, pos); }
    Token new14(int line, int pos) { return new TElse(line, pos); }
    Token new15(int line, int pos) { return new TDo(line, pos); }
    Token new16(int line, int pos) { return new TAssign(line, pos); }
    Token new17(String text, int line, int pos) { return new TCompare(text, line, pos); }
    Token new18(int line, int pos) { return new TPlus(line, pos); }
    Token new19(int line, int pos) { return new TMinus(line, pos); }
    Token new20(int line, int pos) { return new TMult(line, pos); }
    Token new21(int line, int pos) { return new TDiv(line, pos); }
    Token new22(int line, int pos) { return new TLPar(line, pos); }
    Token new23(int line, int pos) { return new TRPar(line, pos); }
    Token new24(int line, int pos) { return new TLBrace(line, pos); }
    Token new25(int line, int pos) { return new TRBrace(line, pos); }
    Token new26(int line, int pos) { return new TLBracket(line, pos); }
    Token new27(int line, int pos) { return new TRBracket(line, pos); }
    Token new28(int line, int pos) { return new TComma(line, pos); }
    Token new29(int line, int pos) { return new TSemi(line, pos); }
    Token new30(String text, int line, int pos) { return new TIdentifier(text, line, pos); }
    Token new31(String text, int line, int pos) { return new TNumber(text, line, pos); }
    Token new32(String text, int line, int pos) { return new TMisc(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 3}, {14, 31, 1}, {32, 32, 4}, {33, 33, 5}, {34, 39, 1}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 57, 14}, {58, 58, 1}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {63, 64, 1}, {65, 82, 19}, {83, 83, 20}, {84, 90, 19}, {91, 91, 21}, {92, 92, 1}, {93, 93, 22}, {94, 96, 1}, {97, 97, 23}, {98, 101, 24}, {102, 102, 25}, {103, 103, 26}, {104, 104, 27}, {105, 105, 28}, {106, 106, 24}, {107, 107, 29}, {108, 108, 24}, {109, 109, 30}, {110, 110, 24}, {111, 111, 31}, {112, 114, 24}, {115, 115, 32}, {116, 116, 33}, {117, 117, 34}, {118, 118, 35}, {119, 122, 24}, {123, 123, 36}, {124, 124, 1}, {125, 125, 37}, {126, 65535, 1}, },
            {},
            {},
            {},
            {},
            {{61, 61, 38}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 39}, },
            {{42, 42, 40}, {47, 47, 41}, },
            {{46, 46, 42}, {48, 57, 43}, {69, 69, 44}, {101, 101, 44}, },
            {},
            {{61, 61, 45}, },
            {{61, 61, 46}, },
            {{61, 61, 47}, },
            {{48, 57, 48}, {65, 90, 49}, {95, 95, 50}, {97, 122, 51}, },
            {{48, 95, -21}, {97, 109, 51}, {110, 110, 52}, {111, 122, 51}, },
            {},
            {},
            {{48, 109, -22}, {110, 110, 53}, {111, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 107, 51}, {108, 108, 54}, {109, 122, 51}, },
            {{48, 95, -21}, {97, 110, 51}, {111, 111, 55}, {112, 122, 51}, },
            {{48, 95, -21}, {97, 117, 51}, {118, 118, 56}, {119, 122, 51}, },
            {{48, 109, -22}, {110, 110, 57}, {111, 122, 51}, },
            {{48, 107, -27}, {108, 108, 58}, {109, 122, 51}, },
            {{48, 95, -21}, {97, 100, 51}, {101, 101, 59}, {102, 122, 51}, },
            {{48, 95, -21}, {97, 101, 51}, {102, 102, 60}, {103, 122, 51}, },
            {{48, 95, -21}, {97, 115, 51}, {116, 116, 61}, {117, 122, 51}, },
            {{48, 95, -21}, {97, 104, 51}, {105, 105, 62}, {106, 122, 51}, },
            {{48, 95, -21}, {97, 102, 51}, {103, 103, 63}, {104, 122, 51}, },
            {{48, 104, -35}, {105, 105, 64}, {106, 122, 51}, },
            {},
            {},
            {},
            {{48, 57, 39}, {69, 101, -16}, },
            {{0, 41, 65}, {42, 42, 66}, {43, 65535, 65}, },
            {{0, 9, 67}, {10, 10, 68}, {11, 12, 67}, {13, 13, 68}, {14, 65535, 67}, },
            {{48, 57, 69}, {69, 101, -16}, },
            {{46, 101, -16}, },
            {{43, 43, 70}, {45, 45, 70}, {48, 57, 71}, },
            {},
            {},
            {},
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 110, -28}, {111, 111, 72}, {112, 122, 51}, },
            {{48, 95, -21}, {97, 99, 51}, {100, 100, 73}, {101, 122, 51}, },
            {{48, 95, -21}, {97, 120, 51}, {121, 121, 74}, {122, 122, 51}, },
            {{48, 95, -21}, {97, 113, 51}, {114, 114, 75}, {115, 122, 51}, },
            {{48, 104, -35}, {105, 105, 76}, {106, 122, 51}, },
            {{48, 115, -34}, {116, 116, 77}, {117, 122, 51}, },
            {{48, 95, -21}, {97, 97, 78}, {98, 122, 51}, },
            {{48, 109, -22}, {110, 110, 79}, {111, 122, 51}, },
            {{48, 101, -33}, {102, 102, 80}, {103, 122, 51}, },
            {{48, 95, -21}, {97, 97, 81}, {98, 122, 51}, },
            {{48, 107, -27}, {108, 108, 82}, {109, 122, 51}, },
            {{48, 120, -56}, {121, 121, 83}, {122, 122, 51}, },
            {{48, 102, -36}, {103, 103, 84}, {104, 122, 51}, },
            {{0, 65535, -42}, },
            {{0, 41, 85}, {43, 46, 85}, {47, 47, 86}, {48, 65535, 85}, },
            {{0, 65535, -43}, },
            {},
            {{48, 101, -44}, },
            {{48, 57, 71}, },
            {{48, 57, 71}, },
            {{48, 113, -57}, {114, 114, 87}, {115, 122, 51}, },
            {{48, 100, -32}, {101, 101, 88}, {102, 122, 51}, },
            {{48, 99, -55}, {100, 100, 89}, {101, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 114, 51}, {115, 115, 90}, {116, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 114, -78}, {115, 115, 91}, {116, 122, 51}, },
            {{48, 114, -78}, {115, 115, 92}, {116, 122, 51}, },
            {{48, 100, -32}, {101, 101, 93}, {102, 122, 51}, },
            {{48, 115, -34}, {116, 116, 94}, {117, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 107, -27}, {108, 108, 95}, {109, 122, 51}, },
            {{48, 115, -34}, {116, 116, 96}, {117, 122, 51}, },
            {{0, 41, 97}, {42, 42, 98}, {43, 65535, 97}, },
            {},
            {{48, 122, -21}, },
            {{48, 115, -34}, {116, 116, 99}, {117, 122, 51}, },
            {{48, 100, -32}, {101, 101, 100}, {102, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 114, -78}, {115, 115, 101}, {116, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 109, -22}, {110, 110, 102}, {111, 122, 51}, },
            {{48, 104, -35}, {105, 105, 103}, {106, 122, 51}, },
            {{48, 99, -55}, {100, 100, 104}, {101, 122, 51}, },
            {{48, 104, -35}, {105, 105, 105}, {106, 122, 51}, },
            {{0, 65535, -87}, },
            {{0, 41, 85}, {42, 42, 98}, {43, 65535, -68}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 100, -32}, {101, 101, 106}, {102, 122, 51}, },
            {{48, 115, -34}, {116, 116, 107}, {117, 122, 51}, },
            {{48, 114, -78}, {115, 115, 108}, {116, 122, 51}, },
            {{48, 104, -35}, {105, 105, 109}, {106, 122, 51}, },
            {{48, 102, -36}, {103, 103, 110}, {104, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 107, -27}, {108, 108, 111}, {109, 122, 51}, },
            {{48, 95, -21}, {97, 106, 51}, {107, 107, 112}, {108, 122, 51}, },
            {{48, 102, -36}, {103, 103, 113}, {104, 122, 51}, },
            {{48, 114, -78}, {115, 115, 114}, {116, 122, 51}, },
            {{48, 104, -35}, {105, 105, 115}, {106, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 115, -34}, {116, 116, 116}, {117, 122, 51}, },
            {{48, 102, -36}, {103, 103, 117}, {104, 122, 51}, },
            {{48, 100, -32}, {101, 101, 118}, {102, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 32, 2, 2, 2, 32, 22, 23, 20, 18, 28, 19, 32, 21, 31, 29, 17, 16, 17, 30, 30, 26, 27, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 24, 25, 17, 31, -1, -1, 31, 31, -1, 17, 17, 17, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, -1, -1, -1, 0, 31, -1, 31, 30, 30, 30, 15, 30, 9, 30, 30, 30, 30, 11, 30, 30, -1, 1, 8, 30, 30, 13, 30, 12, 30, 30, 30, 30, -1, -1, 14, 10, 30, 30, 30, 30, 30, 3, 30, 30, 30, 30, 30, 5, 6, 30, 30, 30, 4, 7, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
